#!/bin/bash

set -euo pipefail


INPUT="$1"
OUTPUT="$2"

echo "$INPUT"
echo "$OUTPUT"

BASE=$(basename "$INPUT" .rosz)
stack build --profile
unzip -p "$INPUT" "$BASE.ros" | .stack-work/install/x86_64-osx/lts-9.21/8.0.2/bin/battlescribe-roster-parser | jq . > "$OUTPUT"


